version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build-and-test:
     executor: win/default
     steps:
       - checkout
       - run: pip install jupyter 
       - run: pip install -r requirements.txt
       - run: .\run
       - run: pip install kaggle
       - run: export KAGGLE_USERNAME = javaproman
       - run: export KAGGLE_KEY = $KAGGLE_KEY
       - run: kaggle competitions submit -f titanic.csv -m 'first' -q titanic
       - store_artifacts:
          path: .\titanic.csv
          destination: .\titanic.csv
workflows:
  main:
    jobs:
      - build-and-test