# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chessbot.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from web import Web

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(348, 305)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_login = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_login.setGeometry(QtCore.QRect(100, 20, 231, 20))
        self.lineEdit_login.setText("")
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.label_login = QtWidgets.QLabel(self.centralwidget)
        self.label_login.setGeometry(QtCore.QRect(10, 20, 81, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_login.setFont(font)
        self.label_login.setAutoFillBackground(False)
        self.label_login.setStyleSheet("background-color:rgb(255, 255, 127)")
        self.label_login.setObjectName("label_login")
        self.label_password = QtWidgets.QLabel(self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(10, 60, 81, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_password.setFont(font)
        self.label_password.setAutoFillBackground(False)
        self.label_password.setStyleSheet("background-color:rgb(255, 255, 127)")
        self.label_password.setObjectName("label_password")
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(100, 60, 231, 20))
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.Button_start = QtWidgets.QPushButton(self.centralwidget)
        self.Button_start.setGeometry(QtCore.QRect(10, 170, 331, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Button_start.setFont(font)
        self.Button_start.setAutoDefault(True)
        self.Button_start.setObjectName("Button_start")
        self.label_bestMove = QtWidgets.QLabel(self.centralwidget)
        self.label_bestMove.setGeometry(QtCore.QRect(20, 230, 81, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_bestMove.setFont(font)
        self.label_bestMove.setAutoFillBackground(False)
        self.label_bestMove.setStyleSheet("background-color:rgb(255, 255, 127)")
        self.label_bestMove.setObjectName("label_bestMove")
        self.lineEdit_bestMove = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_bestMove.setGeometry(QtCore.QRect(110, 230, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_bestMove.setFont(font)
        self.lineEdit_bestMove.setText("")
        self.lineEdit_bestMove.setObjectName("lineEdit_bestMove")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(110, 260, 101, 22))
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.checkBox_autoplay = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_autoplay.setGeometry(QtCore.QRect(250, 220, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_autoplay.setFont(font)
        self.checkBox_autoplay.setObjectName("checkBox_autoplay")
        self.label_time_con = QtWidgets.QLabel(self.centralwidget)
        self.label_time_con.setGeometry(QtCore.QRect(20, 260, 81, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_time_con.setFont(font)
        self.label_time_con.setAutoFillBackground(False)
        self.label_time_con.setStyleSheet("background-color:rgb(255, 255, 127)")
        self.label_time_con.setObjectName("label_time_con")
        self.label_gamer = QtWidgets.QLabel(self.centralwidget)
        self.label_gamer.setGeometry(QtCore.QRect(0, 100, 101, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_gamer.setFont(font)
        self.label_gamer.setAutoFillBackground(False)
        self.label_gamer.setStyleSheet("background-color:rgb(85, 255, 0)")
        self.label_gamer.setObjectName("label_gamer")
        self.lineEdit_gamer = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_gamer.setGeometry(QtCore.QRect(100, 100, 231, 20))
        self.lineEdit_gamer.setObjectName("lineEdit_gamer")
        self.label_timet = QtWidgets.QLabel(self.centralwidget)
        self.label_timet.setGeometry(QtCore.QRect(0, 130, 91, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_timet.setFont(font)
        self.label_timet.setAutoFillBackground(False)
        self.label_timet.setStyleSheet("background-color:rgb(85, 255, 0)")
        self.label_timet.setObjectName("label_timet")
        self.lineEdit_time_think = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_time_think.setGeometry(QtCore.QRect(100, 130, 51, 20))
        self.lineEdit_time_think.setObjectName("lineEdit_time_think")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(160, 130, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_login.setText(_translate("MainWindow", "     Login"))
        self.label_password.setText(_translate("MainWindow", "  Password"))
        self.Button_start.setText(_translate("MainWindow", "Start"))
        self.Button_start.clicked.connect(self.clickButton)
        self.label_bestMove.setText(_translate("MainWindow", "   BestMove"))
        self.comboBox.setItemText(0, _translate("MainWindow", "3 мин"))
        self.comboBox.setItemText(1, _translate("MainWindow", "3+2 мин"))
        self.comboBox.setItemText(2, _translate("MainWindow", "5 мин"))
        self.comboBox.setItemText(3, _translate("MainWindow", "5+3 мин"))
        self.comboBox.setItemText(4, _translate("MainWindow", "10 мин"))
        self.checkBox_autoplay.setText(_translate("MainWindow", "autoplay"))
        self.label_time_con.setText(_translate("MainWindow", "Time control"))
        self.label_gamer.setText(_translate("MainWindow", "game reference"))
        self.label_timet.setText(_translate("MainWindow", "Time thinking"))
        self.lineEdit_time_think.setText(_translate("MainWindow", "2"))
        self.label_7.setText(_translate("MainWindow", "c (мин 2)"))
        self.lineEdit_login.setText("lc_che")
        self.lineEdit_password.setText("123456")
    def clickButton(self):
        str_login=self.lineEdit_login.text()
        str_password=self.lineEdit_password.text()
        web = Web(str_login,str_password)
        web.initialize()